=== yockgen/nanas-os-builder/schema/os-image-composer.schema.json
{
    "$schema": "https://json-schema.org/draft/2020-12/schema",
    "$id": "https://https://raw.githubusercontent.com/intel-innersource/os.linux.tiberos.os-curation-tool/refs/heads/main/schemas/os-image-composer.schema.json",
    "title": "OS Image Composer Input",
    "description": "Defines packages, OS platform/version, output formats, and kernel configuration for the image composer",
    "type": "object",
  
    "properties": {
      "distro": {
        "type": "string",
        "description": "Which OS platform to build against",
        "enum": ["EMT", "AzureLinux", "eLxr"]
      },
      "version": {
        "type": "string",
        "description": "Version of the selected OS platform",
        "pattern": "^[0-9]+(\\.[0-9]+)*$"
      },
      "arch": {
        "type": "string",
        "description": "Architecture of the OS image",
        "enum": ["x86_64", "aarch64"]
      },
      "packages": {
        "type": "array",
        "description": "List of packages to include",
        "items": { "type": "string" },
        "minItems": 1
      },
      "immutable": {
        "type": "boolean",
        "description": "Flags indicating whether each package is immutable"
      },
      "output": {
        "type": "string",
        "description": "Desired output artifact types",
        "items": {
          "type": "string",
          "enum": ["iso", "img", "vhd"]
        },
        "minItems": 1
      },
      "kernel": {
        "type": "object",
        "description": "Kernel version and optional command-line",
        "properties": {
          "version": {
            "type": "string",
            "pattern": "^[0-9]+\\.[0-9]+(\\.[0-9]+)?$",
            "description": "Kernel version to include"
          },
          "cmdline": {
            "type": "string",
            "description": "Additional kernel command-line parameters"
          }
        },
        "required": ["version"],
        "additionalProperties": false
      }
    },
  
    "required": ["distro", "version", "arch", "packages", "immutable", "output", "kernel"],
    "additionalProperties": false,
  
    "allOf": [
        {
          "if":   { "properties": { "distro": { "const": "EMT" } } },
          "then": { "properties": { "version": { "enum": ["3.0", "3.1"] } } }
        },
        {
          "if":   { "properties": { "distro": { "const": "AzureLinux" } } },
          "then": { "properties": { "version": { "enum": ["3"] } } }
        },
        {
          "if":   { "properties": { "distro": { "const": "eLxr" } } },
          "then": { "properties": { "version": { "enum": ["12"] } } }
        }
      ]
    }

=== yockgen/nanas-os-builder/internal/config/testdata/user-input-example.json
{
    "distro": "AzureLinux",
    "version": "3",
    "arch": "x86_64",
    "packages": [
        "cloud-init",        
        "cloud-utils-growpart",
        "dhcpcd",        
        "grubby",
        "hyperv-daemons",
        "netplan",        
        "python3",
        "rsyslog",
        "sgx-backwards-compatibility",
        "WALinuxAgent",        
        "wireless-regdb",
        "zstd-devel-1.5.5-2.azl3.x86_64.rpm"     
    ],
    "immutable": false,
    "output": "iso",
    "kernel": {"version":"6.12"}
}

=== yockgen/nanas-os-builder/internal/config/testdata/minimal-os-image-elxr.json
{
    "distro": "eLxr",
    "version": "12",
    "arch": "x86_64",
    "packages": [
        "systemd-boot",
        "dracut",
        "linux-image-amd64",
        "ca-certificates",
        "vim",
        "sudo",
        "net-tools",
        "openssh-client",
        "openssh-server",
        "procps",
        "less",
        "dbus",
        "policykit-1",
        "curl",
        "wget",
        "ca-certificates",
        "ostree",
        "ostree-boot",
        "python3-apt-ostree",
        "uefi-ext4",
        "systemd-resolved",
        "cloud-guest-utils",
        "xterm"
    ],
    "immutable": true,
    "output": "raw",
    "kernel": { "version": "6.12", "cmdline": "quiet splash" }
}

=== yockgen/nanas-os-builder/testdata/minimal-os-image.json
{
    "distro": "AzureLinux",
    "version": "3",
    "arch": "x86_64",
    "packages": [
		"bash",
        "ca-certificates",
        "ca-certificates-base",
        "dbus",
        "dracut-hostonly",
        "e2fsprogs",
        "filesystem",
        "grub2",
        "grub2-efi-binary",
        "iana-etc",
        "initramfs",
        "iproute",
        "iputils",
        "irqbalance",
        "ncurses-libs",
        "openssl",
        "rpm",
        "rpm-libs",
        "shadow-utils",
        "shim",
        "sudo",
        "systemd",
        "systemd-networkd",
        "systemd-resolved",
        "systemd-udev",
        "tdnf",
        "tdnf-plugin-repogpgcheck",
        "util-linux",
        "zlib"
	],
    "immutable": true,
    "output": "raw",
    "kernel": { "version": "6.12", "cmdline": "quiet splash" }
}
